version: "3"
services:
  decent-slack-receiver:
    depends_on:
      - rabbitmq
    env_file:
      - .env
    build: .
    ports:
      - "8080:80"
  rabbitmq:
    image: "rabbitmq:management-alpine"
    ports:
      - "15672:15672"
